import re, pathlib, sys
ROOT = pathlib.Path("/home/user/huchu")

def edit(path, old, new, count=1):
    p = ROOT / path
    s = p.read_text()
    n = s.count(old)
    assert n == count, f"{path}: expected {count} of {old[:60]!r}, found {n}"
    p.write_text(s.replace(old, new))
    print("edited", path)

# 1. plan changelog row
ROW = ("| 2026-09-06 | — | **Phase 3.1a executed: the school's routes and pages live in the module; the host composes them.** "
       "The first half of the Campus cut. `app/api/v2/schools/**`, `app/api/v2/portal/**` and `app/api/public/schools/**` (172 route files) "
       "moved to `packages/modules/campus/api/` and `app/schools/**`, the three portals' pages and `app/c/[token]` (60 page, layout and loading files) "
       "to `packages/modules/campus/pages/`, on the same relative paths a host serves them at. The host's `app/` tree keeps one thin file per route "
       "and page — a re-export of exactly the names the module's file exports, `\"use client\"` kept where the module's page is a client module — "
       "written by `scripts/compose-host.mjs` (`pnpm compose apps/legacy campus`), which parses each module file with the TypeScript compiler so a "
       "handler that gains a `PUT` regenerates as one. Nothing a tenant sees changes: the URLs, the guards, the proxy's matchers and the gate audit "
       "read the same. The one seam: the route handlers and pages read the session through `getServerSession(authOptions)` from the host's auth "
       "config; they read it through the kernel's `getCurrentAuthSession()` now (44 files), which the host's `modules.ts` already provides through "
       "`registerAuthOptions`, so a module's route runs under whichever host composed it. The route-guard coverage test moved back into the package "
       "(it scans the module's `api/v2/schools`); the fee-fiscalisation test stays in the host as `lib/host/schools-fee-fiscalisation.test.ts` because "
       "it drives the books' replay route too. What 3.1b does next: the same for the shared modules' routes and pages, so a product host is a "
       "module list and nothing else. |\n")
edit("docs/rollout/product-split-plan.md",
     "| Date | Commit | Description |\n|---|---|---|\n",
     "| Date | Commit | Description |\n|---|---|---|\n" + ROW)

# 2. AGENTS.md — host composition of routes and pages
edit("AGENTS.md",
     "never the package entry, which may carry server hooks.\n",
     "never the package entry, which may carry server hooks.\n"
     "- A module's route handlers live under `packages/modules/<id>/api/**/route.ts` and its screens under `packages/modules/<id>/pages/**/{page,layout,loading,…}.tsx`, on the relative paths a host serves them at. A host's `app/` tree holds one thin file per route and page, re-exporting the module's — generated, never written by hand: `pnpm compose apps/legacy campus` (`scripts/compose-host.mjs`) rewrites them from what each module file exports. Add or change a route in the module, then run it again; a file under a composed directory that is not a re-export is a bug. A route or page in a package reads the session through `@corelithzw/platform/auth-core/session` (`getCurrentAuthSession`), never through a host's `authOptions`. Modules whose routes have not moved yet keep them in `apps/legacy/app/` as before.\n")
edit("AGENTS.md",
     "- `scripts/` at the root holds the agent guardrail hooks only.\n",
     "- `scripts/` at the root holds the agent guardrail hooks and `compose-host.mjs`, the host composer.\n")

# 3. runbook §6
edit("docs/rollout/product-split-deployment.md",
     "- `apps/legacy` typechecks in about the same time as before;",
     "- A module's route handlers and pages live in its package once it has been cut for a\n"
     "  product host (Campus first: `packages/modules/campus/api/**`, `packages/modules/campus/pages/**`);\n"
     "  the host's `app/` tree carries a generated one-line re-export for each, so the URLs, the\n"
     "  proxy's matchers and the gate audit are unchanged and production needs nothing. After adding\n"
     "  or renaming a route in such a module run `pnpm compose apps/legacy <module>` and commit the\n"
     "  regenerated files; the app's typecheck fails on a stale re-export rather than serving one.\n"
     "- `apps/legacy` typechecks in about the same time as before;")

# 4. README
edit("README.md",
     "| `app/` | Next.js App Router pages, layouts, and API routes. Feature modules are grouped by route family. |",
     "| `app/` | Next.js App Router pages, layouts, and API routes. Feature modules are grouped by route family. Where a module has been cut for a product host (Campus: `app/schools`, `app/portal/{parent,student,teacher}`, `app/c`, `app/api/v2/schools`, `app/api/v2/portal`, `app/api/public/schools`) the files here are one-line re-exports generated by `pnpm compose apps/legacy <module>`; edit the module, not these. |")
edit("README.md",
     "   - Add route handlers under `app/api/<domain>/` or `app/api/v2/<domain>/`.\n",
     "   - Add route handlers under `app/api/<domain>/` or `app/api/v2/<domain>/` — or, for a module whose routes live in its package (`packages/modules/<id>/api/`), there, then `pnpm compose apps/legacy <id>`.\n")
edit("README.md",
     "   - Add pages under `app/<module>/`.\n",
     "   - Add pages under `app/<module>/` — or, for a module whose pages live in its package (`packages/modules/<id>/pages/`), there, then `pnpm compose apps/legacy <id>`.\n")

# 5. campus README
edit("packages/modules/campus/README.md",
     "components/         the screens, the portals, the master-data panels\n",
     "components/         the screens, the portals, the master-data panels\n"
     "api/                the route handlers (v2/schools, v2/portal, public/schools), on the paths a host serves them at\n"
     "pages/              the pages and layouts (schools, the three portals, the claim page c/[token])\n")
edit("packages/modules/campus/README.md",
     "The API routes and the pages stay in the host until the Campus host composes\nthis module; the manifest id stays `schools`, the schema's name for it.\n",
     "A host composes the routes and pages with `pnpm compose <host dir> campus`\n(`scripts/compose-host.mjs`), which writes a one-line re-export for each into\nthe host's `app/` tree. Routes and pages read the session through the kernel\n(`getCurrentAuthSession`), never a host's auth config. The manifest id stays\n`schools`, the schema's name for it.\n")

# 6. root package.json — compose script
edit("package.json",
     '    "legacy": "pnpm --filter @corelithzw/legacy run",\n',
     '    "legacy": "pnpm --filter @corelithzw/legacy run",\n    "compose": "node scripts/compose-host.mjs",\n')
print("done")
