import pathlib, re, os
ROOT = pathlib.Path("/home/user/huchu")
def edit(path, old, new, count=1):
    p = ROOT / path; s = p.read_text(); n = s.count(old)
    assert n == count, f"{path}: expected {count} of {old[:50]!r}, found {n}"
    p.write_text(s.replace(old, new)); print("edited", path)

ROW = ("| 2026-09-06 | — | **Phase 3.1b-2 executed: every shared module's routes and pages in its package; the host composed from thirteen.** "
       "After the school, the route handlers and pages of every other module (642 files) left `apps/legacy/app` for `packages/modules/<id>/{api,pages}`, "
       "on the paths a host serves them at, and the host's tree is 885 generated re-exports. The tests that scan those trees went with them (the HR and "
       "retail route-guard coverage, the POS host pages, the retail page-actions budget); the gold audit helper is gold's; the v2 collection stub is "
       "the kernel's. Six seams, so that no route names a module its manifest does not require: the books announce a sales invoice or receipt "
       "(`sales-hooks.ts`) and the host registers the CRM's listeners; the fiscal drain gains a sweep registry beside its issuers and the school "
       "finds its own unfiscalised receipts; the shared-record guard asks the module that owns the record type (`registerRecordSubjectGuard`); a "
       "document source declares its feature keys and its authorisation (`access`, `authorize`) and the render route asks the registry; the "
       "searchable-option type is the ui's; maintenance requires books and stock requires books and documents, as their routes and pages always "
       "did. What remains in the host's tree: 48 kernel and host API files and the workspace, marketing, admin and dashboard pages — 3.1b-3 takes "
       "the kernel's routes, the auth options and the proxy into the kernel, 3.1b-4 the workspace pages into the shell; the marketing site, the "
       "admin console, the executive dashboard and the cross-module search stay with the host on purpose. |\n")
edit("docs/rollout/product-split-plan.md", "| Date | Commit | Description |\n|---|---|---|\n", "| Date | Commit | Description |\n|---|---|---|\n" + ROW)

edit("README.md",
     "Where a module has been cut for a product host (Campus: `app/schools`, `app/portal/{parent,student,teacher}`, `app/c`, `app/api/v2/schools`, `app/api/v2/portal`, `app/api/public/schools`) the files here are one-line re-exports generated by `pnpm compose apps/legacy <module>`; edit the module, not these. |",
     "Every module's routes and pages live in its package (`packages/modules/<id>/{api,pages}`); the files here for them are one-line re-exports generated by `pnpm compose apps/legacy <module>…`, so edit the module, not these. What is written by hand here: the kernel's routes (until 3.1b-3), the workspace pages, the marketing site (`app/home`), the admin console, the executive dashboard, the cross-module search. |")

edit("AGENTS.md",
     "Modules whose routes have not moved yet keep them in `apps/legacy/app/` as before.\n",
     "Every module's routes and pages have moved; what `apps/legacy/app/` still holds by hand is the kernel's routes (until they move to `packages/platform/api`), the workspace pages, the marketing site, the admin console, the executive dashboard and the cross-module search. When a route needs another module's code, it goes through a registry the host fills (`sales-hooks`, `registerFiscalDrainSweep`, `registerRecordSubjectGuard`, a document source's `access`/`authorize`), never a direct import — the boundary test holds each package to its manifest.\n")

edit("docs/rollout/product-split-deployment.md",
     "- A module's route handlers and pages live in its package once it has been cut for a\n  product host (Campus first: `packages/modules/campus/api/**`, `packages/modules/campus/pages/**`);\n  the host's `app/` tree carries a generated one-line re-export for each, so the URLs, the\n  proxy's matchers and the gate audit are unchanged and production needs nothing. After adding\n  or renaming a route in such a module run `pnpm compose apps/legacy <module>` and commit the\n  regenerated files; the app's typecheck fails on a stale re-export rather than serving one.\n",
     "- Every module's route handlers and pages live in its package (`packages/modules/<id>/api/**`,\n  `packages/modules/<id>/pages/**`); the host's `app/` tree carries a generated one-line re-export\n  for each, so the URLs, the proxy's matchers and the gate audit are unchanged and production\n  needs nothing. After adding or renaming a route in a module run\n  `pnpm compose apps/legacy <module>` and commit the regenerated files; the app's typecheck fails\n  on a stale re-export rather than serving one.\n")

# module READMEs: the layout gains api/ and pages/, the requires line matches the manifest, the "stays in the host" passages go
PASSAGES = {
    "compliance": ("The API routes, the notification emitters and the pages stay in the host until\nthe first product host composes this module.\n",
                   "A host composes the routes and pages with `pnpm compose <host dir> compliance`.\n"),
    "crm": ("The API routes, the pages and the public token pages stay in the host until\nthe CRM host composes this module.\n",
            "A host composes the routes, the pages and the public token pages with\n`pnpm compose <host dir> crm`.\n"),
    "maintenance": ("The API routes, the notification emitters and the pages stay in the host until\nthe first product host composes this module.\n",
                    "A host composes the routes and pages with `pnpm compose <host dir> maintenance`.\n"),
    "sell": ("The API routes and the pages stay in the host until the Sell host composes\nthis module; the manifest id stays `retail`, the schema's name for it.\n",
             "A host composes the routes, the pages and the POS portal with\n`pnpm compose <host dir> sell`; the manifest id stays `retail`, the schema's name for it.\n"),
}
for mod, (old, new) in PASSAGES.items():
    edit(f"packages/modules/{mod}/README.md", old, new)

for mod in ["books", "compliance", "crm", "documents", "gold", "maintenance", "notifications", "offline", "people", "records", "sell", "stock"]:
    p = ROOT / f"packages/modules/{mod}/README.md"; s = p.read_text()
    lines = s.split("\n")
    idx = next(i for i, l in enumerate(lines) if l.startswith("manifest.ts"))
    col = len(lines[idx]) - len(lines[idx][len("manifest.ts"):].lstrip())
    has_api = (ROOT / f"packages/modules/{mod}/api").exists(); has_pages = (ROOT / f"packages/modules/{mod}/pages").exists()
    add = []
    if has_api and not any(l.startswith("api/") for l in lines): add.append("api/".ljust(col) + "the route handlers, on the paths a host serves them at")
    if has_pages and not any(l.startswith("pages/") for l in lines): add.append("pages/".ljust(col) + "the pages and layouts, on the paths a host serves them at")
    # the requires line reads from the manifest
    mf = (ROOT / f"packages/modules/{mod}/manifest.ts").read_text()
    rm = re.search(r'requires: \[([^\]]*)\]', mf)
    reqs = [x.strip().strip('"') for x in rm.group(1).split(",") if x.strip()] if rm else []
    mid = re.search(r'id: "([a-z]+)"', mf).group(1)
    lines[idx] = "manifest.ts".ljust(col) + f'id "{mid}"; requires ' + (", ".join(reqs) if reqs else "nothing")
    lines[idx + 1:idx + 1] = add
    p.write_text("\n".join(lines)); print("layout", mod, "+", len(add), "lines; requires", reqs)
print("done")
