#!/usr/bin/env python3
"""3.1b-4: the workspace pages and their components into the shell; the two module-owned preference screens into their modules.
Steps: seams move rewrite compose deps check (default: all)."""
import os, re, json, subprocess, sys
ROOT = "/home/user/huchu"; APP = f"{ROOT}/apps/legacy"; PK = f"{ROOT}/packages"; SH = f"{PK}/shell"; MOD = f"{PK}/modules"
steps = sys.argv[1:] or ["all"]
def want(x): return "all" in steps or x in steps
def sh(c): subprocess.run(c, shell=True, check=True, cwd=ROOT)
def read(p): return open(p).read()
def write(p, s): os.makedirs(os.path.dirname(p), exist_ok=True); open(p, "w").write(s)
def edit(p, old, new, count=1):
    s = read(p); n = s.count(old)
    assert n == count, f"{os.path.relpath(p, ROOT)}: expected {count} of {old[:70]!r}, found {n}"
    write(p, s.replace(old, new))
def walk(base, exts=(".ts", ".tsx")):
    for dp, dn, fn in os.walk(base):
        dn[:] = [d for d in dn if d not in ("node_modules", ".next", ".turbo")]
        for f in fn:
            if f.endswith(exts): yield os.path.join(dp, f)
def move_tree(src, dst):
    if not os.path.exists(src):
        assert os.path.exists(dst), f"neither {src} nor {dst} exists"; return
    if os.path.isfile(src):
        os.makedirs(os.path.dirname(dst), exist_ok=True); sh(f'git mv "{src}" "{dst}"'); return
    for dp, dn, fn in os.walk(src):
        rel = os.path.relpath(dp, src); target = os.path.join(dst, rel) if rel != "." else dst
        os.makedirs(target, exist_ok=True)
        for f in fn:
            full = os.path.join(dp, f)
            # a file the composer generated belongs to another package's tree: dropped here, regenerated by compose
            if f.endswith((".ts", ".tsx")) and "Composed from" in read(full):
                sh(f'git rm -q "{full}"'); continue
            sh(f'git mv "{full}" "{os.path.join(target, f)}"')
    sh(f'rm -rf "{src}"')
def relativise(pkg_dir, spec_prefix):
    m = 0
    for p in walk(pkg_dir):
        s = read(p); d = os.path.dirname(p)
        def repl(mm):
            t = mm.group(2)
            if not t.startswith(spec_prefix): return mm.group(0)
            r = os.path.relpath(os.path.join(pkg_dir, t[len(spec_prefix):]), d)
            return f'{mm.group(1)}{r if r.startswith(".") else "./" + r}{mm.group(1)}'
        new = re.compile(r'(["\'])(' + re.escape(spec_prefix) + r'[^"\']+)\1').sub(repl, s)
        if new != s: write(p, new); m += 1
    return m

SHELL_PAGES = ["login", "access-blocked", "help", "status", "preview-host", "preferences", "settings", "user-management",
               "management/users", "management/master-data/page.tsx", "management/master-data/operations/sites"]
MODULE_PAGES = {"people": ["preferences/organization/departments"], "notifications": ["preferences/notifications"]}
# host components → shell paths (a directory each), and the two module-owned screens
COMPONENT_MOVES = [("components/preferences", "preferences"), ("components/user-management", "user-management"),
                   ("components/status", "status"), ("components/settings/branding", "branding"), ("components/onboarding", "onboarding")]
MODULE_COMPONENTS = {
    "people": [("components/preferences/organization/departments-preferences.tsx", "components/preferences/departments-preferences.tsx")],
    "notifications": [("components/preferences/account/notification-preferences.tsx", "components/preferences/notification-preferences.tsx")],
}
REWRITES = [("@/components/preferences/organization/departments-preferences", "@corelithzw/module-people/components/preferences/departments-preferences"),
            ("@/components/preferences/account/notification-preferences", "@corelithzw/module-notifications/components/preferences/notification-preferences"),
            ("@/components/preferences/", "@corelithzw/shell/preferences/"), ("@/components/user-management/", "@corelithzw/shell/user-management/"),
            ("@/components/status/", "@corelithzw/shell/status/"), ("@/components/settings/branding/", "@corelithzw/shell/branding/"),
            ("@/components/onboarding/", "@corelithzw/shell/onboarding/"), ("@/lib/settings/management-nav", "@corelithzw/shell/management")]

def all_targets():
    for d in SHELL_PAGES: yield f"{APP}/app/{d}"
    for dirs in MODULE_PAGES.values():
        for d in dirs: yield f"{APP}/app/{d}"
    for src, _ in COMPONENT_MOVES: yield f"{APP}/{src}"

if want("seams"):
    n = 0
    for base in all_targets():
        for p in (walk(base) if os.path.isdir(base) else [base]):
            s = read(p)
            if "authOptions" not in s: continue
            new = s.replace("getServerSession(authOptions)", "getCurrentAuthSession()")
            new = re.sub(r'import \{ authOptions \} from "@/lib/auth";?\n', "", new)
            if "getServerSession" not in new.replace("import { getServerSession }", ""):
                new = re.sub(r'import \{ getServerSession \} from "next-auth";?\n', 'import { getCurrentAuthSession } from "@corelithzw/platform/auth-core/session";\n', new)
            else:
                new = new.replace('import { getServerSession } from "next-auth";', 'import { getServerSession } from "next-auth";\nimport { getCurrentAuthSession } from "@corelithzw/platform/auth-core/session";')
            assert "authOptions" not in new, p
            write(p, new); n += 1
    print("session seam:", n)
    # every importer of the moved components reads the new home (the host's app shell included)
    m = 0
    for p in walk(APP):
        s = read(p); new = s
        for old, newp in REWRITES: new = new.replace(f'"{old}', f'"{newp}')
        if new != s: write(p, new); m += 1
    print("rewrote importers:", m)
    # the hub page reads the management navigation the host registered in the shell
    hub = f"{APP}/app/management/master-data/page.tsx"
    assert '"@corelithzw/shell/management"' in read(hub), "hub page rewrite"

if want("move"):
    for mod, entries in MODULE_COMPONENTS.items():
        for src, dst in entries: move_tree(f"{APP}/{src}", f"{MOD}/{mod}/{dst}")
    for mod, dirs in MODULE_PAGES.items():
        for d in dirs: move_tree(f"{APP}/app/{d}", f"{MOD}/{mod}/pages/{d}")
    for src, dst in COMPONENT_MOVES: move_tree(f"{APP}/{src}", f"{SH}/{dst}")
    for d in SHELL_PAGES: move_tree(f"{APP}/app/{d}", f"{SH}/pages/{d}")
    for leftover in ("components/settings",):
        if os.path.isdir(f"{APP}/{leftover}") and not any(walk(f"{APP}/{leftover}")): sh(f'rm -rf "{APP}/{leftover}"')
    print("moved")

if want("rewrite"):
    print("relativised shell:", relativise(SH, "@corelithzw/shell/"))
    for mod in MODULE_PAGES: print(f"relativised {mod}:", relativise(f"{MOD}/{mod}", f"@corelithzw/module-{mod}/"))

if want("compose"):
    sh("node scripts/compose-host.mjs apps/legacy shell people notifications")

if want("deps"):
    legacy = json.load(open(f"{APP}/package.json"))
    versions = {**legacy.get("devDependencies", {}), **legacy.get("dependencies", {})}
    for pkg_dir in (SH, f"{MOD}/people", f"{MOD}/notifications"):
        pj = f"{pkg_dir}/package.json"; d = json.load(open(pj))
        have = set(d.get("dependencies", {})) | set(d.get("peerDependencies", {})) | set(d.get("devDependencies", {}))
        bare = set()
        for p in walk(pkg_dir):
            for m in re.finditer(r'from "([^"]+)"', read(p)):
                spec = m.group(1)
                if spec.startswith((".", "@/", "node:")): continue
                pkg = "/".join(spec.split("/")[:2]) if spec.startswith("@") else spec.split("/")[0]
                if pkg in ("next", "react", "react-dom") or pkg in have or pkg in ("fs", "path", "crypto", "http", "stream", "buffer", "os", "url", "events", "util"): continue
                if pkg.startswith("@corelithzw/module-") and pkg_dir != SH: continue
                bare.add(pkg)
        added = []
        for pkg in sorted(bare):
            if pkg.startswith("@corelithzw/") and pkg != "@corelithzw/react":
                d.setdefault("dependencies", {})[pkg] = "workspace:*"; added.append(pkg); continue
            if pkg not in versions: print(f"!! {os.path.basename(pkg_dir)}: no version known for {pkg}"); continue
            d.setdefault("devDependencies" if pkg.startswith("@types/") else "dependencies", {})[pkg] = versions[pkg]; added.append(pkg)
        if added:
            for k in ("dependencies", "devDependencies"):
                if k in d: d[k] = dict(sorted(d[k].items()))
            write(pj, json.dumps(d, indent=2) + "\n"); print(os.path.basename(pkg_dir), "deps added:", added)

if want("check"):
    left = [os.path.relpath(p, SH) for p in walk(SH) if re.search(r'["\']@/', read(p))]
    print("shell files importing '@/':", left or "none")
    mods = [os.path.relpath(p, SH) for p in walk(SH) if "@corelithzw/module-" in read(p)]
    print("shell files naming a module:", mods or "none")
    left2 = [os.path.relpath(p, MOD) for mod in MODULE_PAGES for p in walk(f"{MOD}/{mod}") if re.search(r'["\']@/', read(p))]
    print("module files importing '@/':", left2 or "none")
    pages_left = sorted({os.path.relpath(p, f"{APP}/app") for p in walk(f"{APP}/app") if "Composed from" not in read(p) and not p.startswith(f"{APP}/app/api/")})
    print("host page files not composed:", len(pages_left)); print("  " + "\n  ".join(pages_left))
