import { prisma } from "@/lib/prisma";
import { getEffectiveBrandingForCompany } from "@/lib/platform/branding";
import type { CompanyBrandingSnapshot } from "@/lib/documents/types";

export async function getDocumentBranding(companyId: string): Promise<CompanyBrandingSnapshot> {
  const [effective, raw] = await Promise.all([
    getEffectiveBrandingForCompany(companyId),
    prisma.companyBranding.findUnique({
      where: { companyId },
      select: {
        legalName: true,
        tradingName: true,
        registrationNumber: true,
        taxNumber: true,
        vatNumber: true,
        email: true,
        phone: true,
        website: true,
        physicalAddress: true,
        postalAddress: true,
        bankName: true,
        bankAccountName: true,
        bankAccountNumber: true,
        bankSwiftCode: true,
        bankIban: true,
        defaultFooterText: true,
        legalDisclaimer: true,
        paymentTerms: true,
        logoUrl: true,
        secondaryLogoUrl: true,
        signatureUrl: true,
        stampUrl: true,
        documentLocale: true,
        dateFormat: true,
        timeFormat: true,
        numberFormat: true,
        currencyDisplayMode: true,
      },
    }),
  ]);

  return {
    displayName: effective.displayName,
    fontFamily: effective.fontFamily,
    primaryColor: effective.colors.primary,
    secondaryColor: effective.colors.secondary,
    accentColor: effective.colors.accent,
    legalName: raw?.legalName ?? null,
    tradingName: raw?.tradingName ?? null,
    registrationNumber: raw?.registrationNumber ?? null,
    taxNumber: raw?.taxNumber ?? null,
    vatNumber: raw?.vatNumber ?? null,
    email: raw?.email ?? null,
    phone: raw?.phone ?? null,
    website: raw?.website ?? null,
    physicalAddress: raw?.physicalAddress ?? null,
    postalAddress: raw?.postalAddress ?? null,
    bankName: raw?.bankName ?? null,
    bankAccountName: raw?.bankAccountName ?? null,
    bankAccountNumber: raw?.bankAccountNumber ?? null,
    bankSwiftCode: raw?.bankSwiftCode ?? null,
    bankIban: raw?.bankIban ?? null,
    defaultFooterText: raw?.defaultFooterText ?? null,
    legalDisclaimer: raw?.legalDisclaimer ?? null,
    paymentTerms: raw?.paymentTerms ?? null,
    logoUrl: raw?.logoUrl ?? null,
    secondaryLogoUrl: raw?.secondaryLogoUrl ?? null,
    signatureUrl: raw?.signatureUrl ?? null,
    stampUrl: raw?.stampUrl ?? null,
    documentLocale: raw?.documentLocale ?? null,
    dateFormat: raw?.dateFormat ?? null,
    timeFormat: raw?.timeFormat ?? null,
    numberFormat: raw?.numberFormat ?? null,
    currencyDisplayMode: raw?.currencyDisplayMode ?? null,
  };
}
