export const mockInventory = [
  {
    id: "1",
    code: "FUEL-001",
    name: "Diesel",
    category: "FUEL",
    unit: "litres",
    currentStock: 450,
    minStock: 500,
    maxStock: 2000,
    location: "Main Store",
    unitCost: 1.65,
    status: "low",
  },
  {
    id: "2",
    code: "SPARE-012",
    name: "Crusher Jaw Plates",
    category: "SPARES",
    unit: "pieces",
    currentStock: 4,
    minStock: 2,
    maxStock: 10,
    location: "Workshop",
    unitCost: 450,
    status: "ok",
  },
  {
    id: "3",
    code: "CONS-008",
    name: "Grinding Media (Balls)",
    category: "CONSUMABLES",
    unit: "kg",
    currentStock: 180,
    minStock: 200,
    maxStock: 1000,
    location: "Mill Store",
    unitCost: 2.5,
    status: "low",
  },
  {
    id: "4",
    code: "PPE-015",
    name: "Safety Helmets",
    category: "PPE",
    unit: "pieces",
    currentStock: 25,
    minStock: 15,
    maxStock: 50,
    location: "Main Store",
    unitCost: 12,
    status: "ok",
  },
  {
    id: "5",
    code: "REAG-003",
    name: "Cyanide (NaCN)",
    category: "REAGENTS",
    unit: "kg",
    currentStock: 85,
    minStock: 50,
    maxStock: 200,
    location: "Secure Store",
    unitCost: 8.5,
    status: "ok",
  },
  {
    id: "6",
    code: "SPARE-024",
    name: "Pump Impellers",
    category: "SPARES",
    unit: "pieces",
    currentStock: 1,
    minStock: 3,
    maxStock: 10,
    location: "Workshop",
    unitCost: 180,
    status: "critical",
  },
];

export const mockFuelLedger = [
  {
    date: "2026-01-08",
    type: "issue",
    equipment: "Generator 1",
    quantity: 120,
    opening: 570,
    closing: 450,
    requestedBy: "Night Shift",
    approvedBy: "Site Manager",
  },
  {
    date: "2026-01-07",
    type: "receipt",
    supplier: "Delta Fuels",
    quantity: 1500,
    opening: 70,
    closing: 1570,
    receivedBy: "Stores Clerk",
    invoiceNo: "INV-2401",
  },
  {
    date: "2026-01-07",
    type: "issue",
    equipment: "Crusher",
    quantity: 85,
    opening: 1570,
    closing: 1485,
    requestedBy: "Day Shift",
    approvedBy: "Site Manager",
  },
  {
    date: "2026-01-07",
    type: "issue",
    equipment: "Haul Trucks",
    quantity: 915,
    opening: 1485,
    closing: 570,
    requestedBy: "Day Shift",
    approvedBy: "Supervisor",
  },
];

export const mockRecentMovements = [
  {
    id: "1",
    item: "Grinding Media (Balls)",
    type: "issue",
    quantity: 50,
    unit: "kg",
    issuedTo: "Mill Section",
    requestedBy: "J. Moyo",
    timestamp: "2026-01-08 14:30",
  },
  {
    id: "2",
    item: "Diesel",
    type: "issue",
    quantity: 120,
    unit: "litres",
    issuedTo: "Generator 1",
    requestedBy: "Night Shift",
    timestamp: "2026-01-08 06:00",
  },
  {
    id: "3",
    item: "Safety Helmets",
    type: "issue",
    quantity: 3,
    unit: "pieces",
    issuedTo: "New Hires",
    requestedBy: "HR",
    timestamp: "2026-01-07 10:15",
  },
  {
    id: "4",
    item: "Diesel",
    type: "receipt",
    quantity: 1500,
    unit: "litres",
    issuedTo: "Main Store",
    requestedBy: "Stores Clerk",
    timestamp: "2026-01-07 09:00",
  },
];
