import type { LucideIcon } from "@/lib/icons";
import {
  At,
  Calculate,
  Calendar,
  Camera,
  CheckCircle,
  Grid3x3,
  Hash,
  Layers,
  ListBullets,
  ListChecks,
  NoteBlank,
  NotePencil,
  Percent,
  Phone,
  Rows,
  Rule,
  Square,
  Star,
  TextAlignLeft,
  TextT,
  Upload,
} from "@/lib/icons";
import type { FieldType } from "@/lib/forms/fields";

/** One filled glyph per kind of question, so the palette reads before its words do. */
export const FIELD_TYPE_ICONS: Record<FieldType, LucideIcon> = {
  text: TextT,
  longText: TextAlignLeft,
  number: Hash,
  email: At,
  phone: Phone,
  date: Calendar,
  select: ListBullets,
  multiSelect: ListChecks,
  checkbox: CheckCircle,
  file: Upload,
  rating: Star,
  length: Rule,
  area: Square,
  areas: Grid3x3,
  count: Calculate,
  reading: Percent,
  run: Rows,
  photos: Camera,
  signature: NotePencil,
  section: Layers,
  note: NoteBlank,
};

