import { ACCOUNT_STATUS_OPTIONS, COMPANY_TYPE_OPTIONS } from "@/lib/crm/record-labels";

import type { RegisterDef } from "../types";

/** Companies: the accounts. Opens A–Z, like the people directory. */
export const COMPANY_REGISTER = {
  key: "COMPANY",
  noun: { one: "company", many: "companies" },
  route: "/crm/companies",
  endpoint: "/api/v2/crm/companies",
  queryKey: ["crm", "companies"],
  layouts: ["TABLE", "LIST", "BOARD"],
  search: { placeholder: "Search companies by name, number or town" },
  filters: [
    { key: "status", label: "Status", kind: "enum", options: ACCOUNT_STATUS_OPTIONS, anyLabel: "Any", pinned: true },
    { key: "type", label: "Type", kind: "enum", options: COMPANY_TYPE_OPTIONS, anyLabel: "All", pinned: true },
    { key: "owner", label: "Owner", kind: "person", anyLabel: "Anyone", pinned: true },
    { key: "city", label: "City", kind: "enum", facet: true, anyLabel: "Anywhere" },
    { key: "tag", label: "Tag", kind: "enum", facet: true, anyLabel: "Any tag" },
    {
      key: "parent",
      label: "Part of",
      kind: "relation",
      relation: "COMPANY",
      anyLabel: "Any",
      offer: false,
    },
    {
      key: "contacted",
      label: "Last contacted",
      kind: "date",
      anyLabel: "Any time",
      presets: ["this-week", "last-7d", "last-30d", "this-month"],
    },
    {
      key: "created",
      label: "Added",
      kind: "date",
      anyLabel: "Any time",
      presets: ["today", "this-week", "this-month", "last-30d"],
    },
    { key: "group", label: "Group", kind: "group", anyLabel: "Any group" },
    { key: "archived", label: "Archived", kind: "boolean", onLabel: "Archived only" },
  ],
  sorts: [
    { key: "name", label: "Name", dir: "asc" },
    { key: "updated", label: "Last updated", dir: "desc" },
    { key: "created", label: "Date added", dir: "desc" },
    { key: "contacted", label: "Last contacted", dir: "desc" },
    { key: "ref", label: "Reference", dir: "asc" },
  ],
  columns: [
    { id: "name", label: "Name", kind: "text", required: true, sort: "name" },
    { id: "ref", label: "Reference", kind: "code", hiddenByDefault: true, sort: "ref" },
    { id: "tradingName", label: "Trading as", kind: "text", hiddenByDefault: true },
    { id: "status", label: "Status", kind: "status" },
    { id: "type", label: "Type", kind: "status" },
    { id: "location", label: "Where", kind: "text" },
    { id: "people", label: "People", kind: "number" },
    { id: "deals", label: "Deals", kind: "number" },
    { id: "owner", label: "Owner", kind: "relation" },
    { id: "email", label: "Email", kind: "email", hiddenByDefault: true },
    { id: "phone", label: "Phone", kind: "phone", hiddenByDefault: true },
    { id: "website", label: "Website", kind: "text", hiddenByDefault: true },
    { id: "industry", label: "Industry", kind: "text", hiddenByDefault: true },
    { id: "parent", label: "Part of", kind: "relation", hiddenByDefault: true },
    { id: "taxNumber", label: "Tax number", kind: "code", hiddenByDefault: true },
    { id: "tags", label: "Tags", kind: "text", hiddenByDefault: true },
    { id: "contacted", label: "Last contacted", kind: "date", hiddenByDefault: true, sort: "contacted" },
    { id: "created", label: "Added", kind: "date", hiddenByDefault: true, sort: "created" },
    { id: "updated", label: "Last updated", kind: "datetime", hiddenByDefault: true, sort: "updated" },
  ],
  views: [
    { key: "all", name: "All companies", state: { filters: {} } },
    { key: "mine", name: "My accounts", state: { filters: { owner: ["me"] } } },
    { key: "customers", name: "Customers", state: { filters: { type: ["CUSTOMER"] } } },
    { key: "prospects", name: "Prospects", state: { filters: { type: ["PROSPECT"] } } },
    { key: "on-hold", name: "On hold", state: { filters: { status: ["ON_HOLD"] } } },
    { key: "unassigned", name: "Unassigned", state: { filters: { owner: ["none"] } } },
    { key: "archived", name: "Archived", state: { filters: { archived: true } } },
  ],
  bulk: ["assign", "status", "group", "archive", "restore"],
  statusOptions: ACCOUNT_STATUS_OPTIONS,
  groupEntity: "COMPANY",
} as const satisfies RegisterDef;
