import type { PayrollCycle, PrismaClient, RunDomain } from "@prisma/client"

import {
  deriveCyclePeriodKey,
  deriveCycleWindow,
  nextCycleAnchor,
  startOfDayUtc,
} from "@/lib/hr-payroll"

type SeedInput = {
  companyId: string
  createdById: string
  domains?: RunDomain[]
  now?: Date
}

type PeriodDraft = {
  companyId: string
  domain: RunDomain
  scopeKey: string
  periodKey: string
  cycle: PayrollCycle
  startDate: Date
  endDate: Date
  dueDate: Date
  isAutoGenerated: boolean
  periodPurpose: "STANDARD"
  createdById: string
}

function domainsToSeed(inputDomains?: RunDomain[]) {
  if (inputDomains && inputDomains.length > 0) {
    return Array.from(new Set(inputDomains))
  }
  return ["PAYROLL", "GOLD_PAYOUT"] as RunDomain[]
}

function cycleForDomain(input: {
  domain: RunDomain
  payrollCycle: PayrollCycle
  goldPayoutCycle: PayrollCycle
}) {
  return input.domain === "GOLD_PAYOUT" ? input.goldPayoutCycle : input.payrollCycle
}

function autoEnabledForDomain(input: {
  domain: RunDomain
  autoGeneratePayrollPeriods: boolean
  autoGenerateGoldPayoutPeriods: boolean
}) {
  return input.domain === "GOLD_PAYOUT"
    ? input.autoGenerateGoldPayoutPeriods
    : input.autoGeneratePayrollPeriods
}

function buildAutoDrafts(input: {
  companyId: string
  createdById: string
  domain: RunDomain
  scopeKey: string
  cycle: PayrollCycle
  horizon: number
  now: Date
}) {
  const drafts: PeriodDraft[] = []
  let anchor = startOfDayUtc(input.now)

  for (let index = 0; index < input.horizon; index += 1) {
    const window = deriveCycleWindow(anchor, input.cycle)
    drafts.push({
      companyId: input.companyId,
      domain: input.domain,
      scopeKey: input.scopeKey,
      periodKey: deriveCyclePeriodKey(window.startDate, input.cycle),
      cycle: input.cycle,
      startDate: window.startDate,
      endDate: window.endDate,
      dueDate: window.endDate,
      isAutoGenerated: true,
      periodPurpose: "STANDARD",
      createdById: input.createdById,
    })
    anchor = nextCycleAnchor(window.startDate, input.cycle)
  }

  return drafts
}

export async function ensureAutoPeriods(
  prisma: PrismaClient,
  input: SeedInput,
) {
  const company = await prisma.company.findUnique({
    where: { id: input.companyId },
    select: {
      payrollCycle: true,
      goldPayoutCycle: true,
      autoGeneratePayrollPeriods: true,
      autoGenerateGoldPayoutPeriods: true,
      periodGenerationHorizon: true,
    },
  })
  if (!company) {
    throw new Error("Company not found while seeding payroll periods")
  }

  const horizon = Math.max(1, Math.min(company.periodGenerationHorizon, 12))
  const now = input.now ?? new Date()
  const targetDomains = domainsToSeed(input.domains)
  const drafts: PeriodDraft[] = []

  for (const domain of targetDomains) {
    if (
      !autoEnabledForDomain({
        domain,
        autoGeneratePayrollPeriods: company.autoGeneratePayrollPeriods,
        autoGenerateGoldPayoutPeriods: company.autoGenerateGoldPayoutPeriods,
      })
    ) {
      continue
    }

    drafts.push(
      ...buildAutoDrafts({
        companyId: input.companyId,
        createdById: input.createdById,
        domain,
        scopeKey: domain === "GOLD_PAYOUT" ? "GOLD" : "PAYROLL",
        cycle: cycleForDomain({
          domain,
          payrollCycle: company.payrollCycle,
          goldPayoutCycle: company.goldPayoutCycle,
        }),
        horizon,
        now,
      }),
    )
  }

  if (drafts.length === 0) {
    return {
      createdCount: 0,
      skippedCount: 0,
      periodKeysCreated: [] as string[],
    }
  }

  const uniqueDrafts = drafts.filter((draft, index, list) => {
    return (
      list.findIndex(
        (item) =>
          item.domain === draft.domain &&
          item.periodKey === draft.periodKey &&
          item.scopeKey === draft.scopeKey,
      ) === index
    )
  })

  const existing = await prisma.payrollPeriod.findMany({
    where: {
      companyId: input.companyId,
      OR: uniqueDrafts.map((draft) => ({
        domain: draft.domain,
        periodKey: draft.periodKey,
        scopeKey: draft.scopeKey,
      })),
    },
    select: {
      domain: true,
      periodKey: true,
      scopeKey: true,
    },
  })
  const existingSet = new Set(
    existing.map((row) => `${row.domain}:${row.scopeKey}:${row.periodKey}`),
  )

  const toCreate = uniqueDrafts.filter(
    (draft) => !existingSet.has(`${draft.domain}:${draft.scopeKey}:${draft.periodKey}`),
  )
  if (toCreate.length > 0) {
    await prisma.payrollPeriod.createMany({
      data: toCreate,
      skipDuplicates: true,
    })
  }

  return {
    createdCount: toCreate.length,
    skippedCount: uniqueDrafts.length - toCreate.length,
    periodKeysCreated: toCreate.map((row) => `${row.domain}:${row.scopeKey}:${row.periodKey}`),
  }
}
