import { NextRequest, NextResponse } from "next/server"
import type { PayrollCycle, RunDomain } from "@prisma/client"
import { z } from "zod"
import {
  errorResponse,
  getPaginationParams,
  paginationResponse,
  successResponse,
  validateSession,
} from "@/lib/api-utils"
import { prisma } from "@/lib/prisma"
import {
  deriveCyclePeriodKey,
  deriveCycleWindow,
  ensureApproverRole,
  monthPeriodKey,
  nextCycleAnchor,
} from "@/lib/hr-payroll"
import { ensureAutoPeriods } from "@/lib/payroll-periods"

const periodSchema = z.object({
  domain: z.enum(["PAYROLL", "GOLD_PAYOUT"]).optional(),
  payoutSource: z.enum(["GOLD", "COMMISSION", "OTHER"]).optional(),
  periodKey: z.string().regex(/^\d{4}-\d{2}(-H[12])?$/).optional(),
  cycle: z.enum(["MONTHLY", "FORTNIGHTLY"]).optional(),
  anchorDate: z
    .string()
    .datetime()
    .or(z.string().regex(/^\d{4}-\d{2}-\d{2}$/))
    .optional(),
  autoGenerateCount: z.number().int().min(1).max(12).optional(),
  startDate: z
    .string()
    .datetime()
    .or(z.string().regex(/^\d{4}-\d{2}-\d{2}$/))
    .optional(),
  endDate: z
    .string()
    .datetime()
    .or(z.string().regex(/^\d{4}-\d{2}-\d{2}$/))
    .optional(),
  dueDate: z
    .string()
    .datetime()
    .or(z.string().regex(/^\d{4}-\d{2}-\d{2}$/))
    .optional(),
  periodPurpose: z.enum(["STANDARD", "CONTRACTOR", "EDGE_CASE"]).optional(),
  appliesToContractorsOnly: z.boolean().optional(),
  employeeScopeIds: z.array(z.string().uuid()).max(500).optional(),
  isAutoGenerated: z.boolean().optional(),
  notes: z.string().max(1000).optional(),
})

function parsePeriodKeyToDate(periodKey: string) {
  if (periodKey.endsWith("-H2")) {
    const ym = periodKey.replace(/-H2$/, "")
    return new Date(`${ym}-16T00:00:00.000Z`)
  }
  const ym = periodKey.replace(/-H1$/, "")
  return new Date(`${ym}-01T00:00:00.000Z`)
}

type PeriodDraft = {
  domain: RunDomain
  payoutSource?: "GOLD" | "COMMISSION" | "OTHER"
  scopeKey: string
  periodKey: string
  cycle: PayrollCycle
  startDate: Date
  endDate: Date
  dueDate: Date
  isAutoGenerated: boolean
  periodPurpose: "STANDARD" | "CONTRACTOR" | "EDGE_CASE"
  appliesToContractorsOnly: boolean
  employeeScopeJson?: string
  notes?: string
}

export async function GET(request: NextRequest) {
  try {
    const sessionResult = await validateSession(request)
    if (sessionResult instanceof NextResponse) return sessionResult
    const { session } = sessionResult
    await ensureAutoPeriods(prisma, {
      companyId: session.user.companyId,
      createdById: session.user.id,
    })
    const { searchParams } = new URL(request.url)
    const { page, limit, skip } = getPaginationParams(request)

    const domain = searchParams.get("domain")
    const payoutSource = searchParams.get("payoutSource")
    const status = searchParams.get("status")
    const cycle = searchParams.get("cycle")
    const periodPurpose = searchParams.get("periodPurpose")
    const isAutoGenerated = searchParams.get("isAutoGenerated")
    const startDate = searchParams.get("startDate")
    const endDate = searchParams.get("endDate")
    const search = searchParams.get("search")?.trim()

    const where: Record<string, unknown> = {
      companyId: session.user.companyId,
    }
    if (domain === "PAYROLL" || domain === "GOLD_PAYOUT") where.domain = domain
    if (payoutSource === "GOLD" || payoutSource === "COMMISSION" || payoutSource === "OTHER") {
      where.payoutSource = payoutSource
    }
    if (status) where.status = status
    if (cycle) where.cycle = cycle
    if (
      periodPurpose === "STANDARD" ||
      periodPurpose === "CONTRACTOR" ||
      periodPurpose === "EDGE_CASE"
    ) {
      where.periodPurpose = periodPurpose
    }
    if (isAutoGenerated === "true") where.isAutoGenerated = true
    if (isAutoGenerated === "false") where.isAutoGenerated = false
    if (startDate) where.startDate = { gte: new Date(startDate) }
    if (endDate) where.endDate = { lte: new Date(endDate) }
    if (search) {
      const normalizedSearch = search.toUpperCase()
      where.OR = [
        { periodKey: { contains: search, mode: "insensitive" } },
        { notes: { contains: search, mode: "insensitive" } },
        ...(normalizedSearch === "PAYROLL" || normalizedSearch === "GOLD_PAYOUT"
          ? [{ domain: normalizedSearch }]
          : []),
        ...(normalizedSearch === "MONTHLY" || normalizedSearch === "FORTNIGHTLY"
          ? [{ cycle: normalizedSearch }]
          : []),
        ...((
          ["DRAFT", "SUBMITTED", "APPROVED", "CLOSED"] as const
        ).includes(
          normalizedSearch as "DRAFT" | "SUBMITTED" | "APPROVED" | "CLOSED",
        )
          ? [{ status: normalizedSearch }]
          : []),
      ]
    }

    const [records, total] = await Promise.all([
      prisma.payrollPeriod.findMany({
        where,
        include: {
          _count: { select: { runs: true } },
          createdBy: { select: { id: true, name: true } },
          approvedBy: { select: { id: true, name: true } },
          runs: {
            select: {
              id: true,
              runNumber: true,
              status: true,
              netTotal: true,
              createdAt: true,
            },
            orderBy: { runNumber: "desc" },
          },
        },
        orderBy: { startDate: "desc" },
        skip,
        take: limit,
      }),
      prisma.payrollPeriod.count({ where }),
    ])

    return successResponse(paginationResponse(records, total, page, limit))
  } catch (error) {
    console.error("[API] GET /api/payroll/periods error:", error)
    return errorResponse("Failed to fetch payroll periods")
  }
}

export async function POST(request: NextRequest) {
  try {
    const sessionResult = await validateSession(request)
    if (sessionResult instanceof NextResponse) return sessionResult
    const { session } = sessionResult
    if (!ensureApproverRole(session)) {
      return errorResponse("Insufficient permissions to create payroll periods", 403)
    }
    const body = await request.json()
    const validated = periodSchema.parse(body)

    const company = await prisma.company.findUnique({
      where: { id: session.user.companyId },
      select: { payrollCycle: true, goldPayoutCycle: true },
    })
    if (!company) {
      return errorResponse("Company not found", 404)
    }

    const domain = validated.domain ?? "PAYROLL"
    const payoutSource =
      domain === "GOLD_PAYOUT" ? (validated.payoutSource ?? "GOLD") : undefined
    const scopeKey = payoutSource ?? domain
    const inferredCycle = validated.periodKey?.includes("-H") ? "FORTNIGHTLY" : undefined
    const defaultCycle =
      domain === "GOLD_PAYOUT" ? company.goldPayoutCycle : company.payrollCycle
    const cycle = validated.cycle ?? inferredCycle ?? defaultCycle
    const periodPurpose = validated.periodPurpose ?? "STANDARD"
    const employeeScopeJson =
      validated.employeeScopeIds && validated.employeeScopeIds.length > 0
        ? JSON.stringify(validated.employeeScopeIds)
        : undefined
    const isAutoGenerated = validated.isAutoGenerated ?? false
    const drafts: PeriodDraft[] = []

    if (validated.startDate || validated.endDate || validated.periodKey) {
      const baseDate = validated.periodKey
        ? parsePeriodKeyToDate(validated.periodKey)
        : validated.startDate
          ? new Date(validated.startDate)
          : new Date()
      const window = deriveCycleWindow(baseDate, cycle)
      const startDate = validated.startDate ? new Date(validated.startDate) : window.startDate
      const endDate = validated.endDate ? new Date(validated.endDate) : window.endDate
      if (endDate < startDate) {
        return errorResponse("End date cannot be before start date", 400)
      }

      drafts.push({
        domain,
        payoutSource,
        scopeKey,
        periodKey:
          validated.periodKey ??
          (cycle === "FORTNIGHTLY"
            ? deriveCyclePeriodKey(startDate, "FORTNIGHTLY")
            : monthPeriodKey(startDate)),
        cycle,
        startDate,
        endDate,
        dueDate: validated.dueDate ? new Date(validated.dueDate) : endDate,
        isAutoGenerated,
        periodPurpose,
        appliesToContractorsOnly: validated.appliesToContractorsOnly ?? false,
        employeeScopeJson,
        notes: validated.notes,
      })
    } else {
      const count = validated.autoGenerateCount ?? 1
      let anchor = validated.anchorDate ? new Date(validated.anchorDate) : new Date()

      for (let i = 0; i < count; i += 1) {
        const window = deriveCycleWindow(anchor, cycle)
        drafts.push({
          domain,
          payoutSource,
          scopeKey,
          periodKey: deriveCyclePeriodKey(window.startDate, cycle),
          cycle,
          startDate: window.startDate,
          endDate: window.endDate,
          dueDate: validated.dueDate ? new Date(validated.dueDate) : window.endDate,
          isAutoGenerated,
          periodPurpose,
          appliesToContractorsOnly: validated.appliesToContractorsOnly ?? false,
          employeeScopeJson,
          notes: validated.notes,
        })
        anchor = nextCycleAnchor(window.startDate, cycle)
      }
    }

    const uniqueDrafts = drafts.filter(
      (draft, index, list) =>
        list.findIndex(
          (item) =>
            item.domain === draft.domain &&
            item.periodKey === draft.periodKey &&
            item.scopeKey === draft.scopeKey,
        ) === index,
    )
    const keys = uniqueDrafts.map((draft) => `${draft.scopeKey}:${draft.periodKey}`)
    const existing = await prisma.payrollPeriod.findMany({
      where: {
        companyId: session.user.companyId,
        domain,
        OR: uniqueDrafts.map((draft) => ({
          periodKey: draft.periodKey,
          scopeKey: draft.scopeKey,
        })),
      },
      select: { periodKey: true, scopeKey: true },
    })
    const existingKeys = new Set(existing.map((row) => `${row.scopeKey}:${row.periodKey}`))
    const toCreate = uniqueDrafts.filter(
      (draft) => !existingKeys.has(`${draft.scopeKey}:${draft.periodKey}`),
    )

    if (toCreate.length === 0) {
      return errorResponse("Payroll periods already exist for the requested cycle window", 409, {
        existingPeriodKeys: keys,
      })
    }

    const created = await prisma.$transaction(
      toCreate.map((draft) =>
        prisma.payrollPeriod.create({
          data: {
            companyId: session.user.companyId,
            domain: draft.domain,
            payoutSource: draft.payoutSource,
            scopeKey: draft.scopeKey,
            periodKey: draft.periodKey,
            cycle: draft.cycle,
            startDate: draft.startDate,
            endDate: draft.endDate,
            dueDate: draft.dueDate,
            isAutoGenerated: draft.isAutoGenerated,
            periodPurpose: draft.periodPurpose,
            appliesToContractorsOnly: draft.appliesToContractorsOnly,
            employeeScopeJson: draft.employeeScopeJson,
            notes: draft.notes,
            createdById: session.user.id,
          },
          include: {
            createdBy: { select: { id: true, name: true } },
          },
        }),
      ),
    )

    if (created.length === 1) {
      return successResponse(
        {
          ...created[0],
          skippedPeriodKeys: keys.filter((key) => existingKeys.has(key)),
        },
        201,
      )
    }

    return successResponse(
      {
        created,
        skippedPeriodKeys: keys.filter((key) => existingKeys.has(key)),
      },
      201,
    )
  } catch (error) {
    if (error instanceof z.ZodError) {
      return errorResponse("Validation failed", 400, error.issues)
    }
    console.error("[API] POST /api/payroll/periods error:", error)
    return errorResponse("Failed to create payroll period")
  }
}
