export const PLATFORM_ADMIN_MANIFEST = {
  org: [
    "list",
    "resolve",
    "detail",
    "provision",
    "previewProvisionBundle",
    "provisionBundle",
    "suggestSubdomains",
    "reserveSubdomain",
    "getSubdomainReservation",
    "suspend",
    "activate",
    "disable",
  ],
  site: ["list", "detail", "create", "update", "activate", "deactivate"],
  subscription: [
    "list",
    "setStatus",
    "listPlans",
    "assignTier",
    "listTemplates",
    "applyTemplate",
    "listBundleCatalog",
    "upsertBundleCatalog",
    "setBundleFeatures",
    "listAddons",
    "setAddon",
    "recomputePricing",
    "health",
    "syncCatalog",
  ],
  feature: ["list", "set"],
  admin: ["list", "create", "activate", "deactivate", "resetPassword"],
  user: ["list", "create", "activate", "deactivate", "resetPassword", "changeRole"],
  audit: ["list", "addNote", "export", "verifyChain"],
  support: ["listRequests", "listSessions", "requestAccess", "approveRequest", "startSession", "endSession", "expireSessions"],
  runbook: ["listDefinitions", "upsertDefinition", "listExecutions", "execute", "setEnabled"],
  health: ["recordMetric", "listMetrics", "listIncidents", "triggerRemediation"],
  contract: ["evaluate", "enforce", "override", "getState"],
  search: ["global"],
} as const;

export type PlatformAdminModule = keyof typeof PLATFORM_ADMIN_MANIFEST;
