import type { PayrollCycle, PrismaClient } from "@corelithzw/db"

import { deriveCyclePeriodKey, deriveCycleWindow, nextCycleAnchor, startOfDayUtc } from "@/lib/workflow/periods"

/**
 * Payroll periods, seeded ahead of time.
 *
 * There is one kind of period. This used to seed two — a `PAYROLL` domain and a
 * `GOLD_PAYOUT` one on a separate cycle, distinguished by a `scopeKey`, so a
 * gold mine's August existed twice and the unique constraint had to carry four
 * columns to allow it. Settlements have their own runs on their own windows, so
 * a period is now just a month (or a fortnight) and `[companyId, periodKey]` is
 * unique.
 */

type SeedInput = {
  companyId: string
  createdById: string
  now?: Date
}

type PeriodDraft = {
  companyId: string
  periodKey: string
  cycle: PayrollCycle
  startDate: Date
  endDate: Date
  dueDate: Date
  isAutoGenerated: boolean
  periodPurpose: "STANDARD"
  createdById: string
}

function buildAutoDrafts(input: {
  companyId: string
  createdById: string
  cycle: PayrollCycle
  horizon: number
  now: Date
}) {
  const drafts: PeriodDraft[] = []
  let anchor = startOfDayUtc(input.now)

  for (let index = 0; index < input.horizon; index += 1) {
    const window = deriveCycleWindow(anchor, input.cycle)
    drafts.push({
      companyId: input.companyId,
      periodKey: deriveCyclePeriodKey(window.startDate, input.cycle),
      cycle: input.cycle,
      startDate: window.startDate,
      endDate: window.endDate,
      dueDate: window.endDate,
      isAutoGenerated: true,
      periodPurpose: "STANDARD",
      createdById: input.createdById,
    })
    anchor = nextCycleAnchor(window.startDate, input.cycle)
  }

  return drafts
}

export async function ensureAutoPeriods(
  prisma: PrismaClient,
  input: SeedInput,
) {
  const company = await prisma.company.findUnique({
    where: { id: input.companyId },
    select: {
      payrollCycle: true,
      autoGeneratePayrollPeriods: true,
      periodGenerationHorizon: true,
    },
  })
  if (!company) {
    throw new Error("Company not found while seeding payroll periods")
  }

  if (!company.autoGeneratePayrollPeriods) {
    return { createdCount: 0, skippedCount: 0, periodKeysCreated: [] as string[] }
  }

  const horizon = Math.max(1, Math.min(company.periodGenerationHorizon, 12))
  const drafts = buildAutoDrafts({
    companyId: input.companyId,
    createdById: input.createdById,
    cycle: company.payrollCycle,
    horizon,
    now: input.now ?? new Date(),
  })

  const uniqueDrafts = drafts.filter(
    (draft, index, list) =>
      list.findIndex((item) => item.periodKey === draft.periodKey) === index,
  )

  const existing = await prisma.payrollPeriod.findMany({
    where: {
      companyId: input.companyId,
      periodKey: { in: uniqueDrafts.map((draft) => draft.periodKey) },
    },
    select: { periodKey: true },
  })
  const existingSet = new Set(existing.map((row) => row.periodKey))

  const toCreate = uniqueDrafts.filter((draft) => !existingSet.has(draft.periodKey))
  if (toCreate.length > 0) {
    await prisma.payrollPeriod.createMany({
      data: toCreate,
      skipDuplicates: true,
    })
  }

  return {
    createdCount: toCreate.length,
    skippedCount: uniqueDrafts.length - toCreate.length,
    periodKeysCreated: toCreate.map((row) => row.periodKey),
  }
}
