import type { FeatureRouteEntry } from "@/lib/platform/gating/types";

export const PAGE_FEATURE_ROUTES: FeatureRouteEntry[] = [
  { scope: "page", prefix: "/login", featureKey: "core.auth.login" },
  { scope: "page", prefix: "/help", featureKey: "core.help.quick-tips" },
  { scope: "page", prefix: "/settings/branding", featureKey: "core.branding.manage" },
  { scope: "page", prefix: "/settings/templates", featureKey: "core.branding.manage" },

  { scope: "page", prefix: "/cctv/live", featureKey: "cctv.live" },
  { scope: "page", prefix: "/cctv/cameras", featureKey: "cctv.cameras" },
  { scope: "page", prefix: "/cctv/nvrs", featureKey: "cctv.nvrs" },
  { scope: "page", prefix: "/cctv/events", featureKey: "cctv.events" },
  { scope: "page", prefix: "/cctv/playback", featureKey: "cctv.playback" },
  { scope: "page", prefix: "/cctv/access-logs", featureKey: "cctv.access-logs" },
  { scope: "page", prefix: "/cctv/overview", featureKey: "cctv.overview" },
  { scope: "page", prefix: "/cctv", featureKey: "cctv.overview" },

  { scope: "page", prefix: "/human-resources/payroll", featureKey: "hr.payroll" },
  { scope: "page", prefix: "/human-resources/disbursements", featureKey: "hr.disbursements" },
  { scope: "page", prefix: "/human-resources/compensation", featureKey: "hr.compensation-rules" },
  { scope: "page", prefix: "/human-resources/shift-groups", featureKey: "hr.employees" },
  { scope: "page", prefix: "/human-resources/salaries", featureKey: "hr.salaries" },
  { scope: "page", prefix: "/human-resources/approvals", featureKey: "hr.approvals-history" },
  { scope: "page", prefix: "/human-resources/incidents", featureKey: "hr.incidents" },
  { scope: "page", prefix: "/human-resources/payouts", featureKey: "hr.gold-payouts" },
  { scope: "page", prefix: "/human-resources", featureKey: "hr.employees" },

  { scope: "page", prefix: "/maintenance/work-orders", featureKey: "maintenance.work-orders" },
  { scope: "page", prefix: "/maintenance/equipment", featureKey: "maintenance.equipment" },
  { scope: "page", prefix: "/maintenance/breakdown", featureKey: "maintenance.breakdowns" },
  { scope: "page", prefix: "/maintenance/schedule", featureKey: "maintenance.schedule" },
  { scope: "page", prefix: "/maintenance", featureKey: "maintenance.dashboard" },

  { scope: "page", prefix: "/stores/movements", featureKey: "stores.movements" },
  { scope: "page", prefix: "/stores/inventory", featureKey: "stores.inventory" },
  { scope: "page", prefix: "/stores/issue", featureKey: "stores.issue" },
  { scope: "page", prefix: "/stores/receive", featureKey: "stores.receive" },
  { scope: "page", prefix: "/stores/fuel", featureKey: "stores.fuel-ledger" },
  { scope: "page", prefix: "/stores/dashboard", featureKey: "stores.dashboard" },
  { scope: "page", prefix: "/stores", featureKey: "stores.dashboard" },

  { scope: "page", prefix: "/accounting/chart-of-accounts", featureKey: "accounting.chart-of-accounts" },
  { scope: "page", prefix: "/accounting/journals", featureKey: "accounting.journals" },
  { scope: "page", prefix: "/accounting/periods", featureKey: "accounting.periods" },
  { scope: "page", prefix: "/accounting/posting-rules", featureKey: "accounting.posting-rules" },
  { scope: "page", prefix: "/accounting/receivables", featureKey: "accounting.ar" },
  { scope: "page", prefix: "/accounting/payables", featureKey: "accounting.ap" },
  { scope: "page", prefix: "/accounting/financial-reports", featureKey: "accounting.financial-statements" },
  { scope: "page", prefix: "/accounting/trial-balance", featureKey: "accounting.trial-balance" },
  { scope: "page", prefix: "/accounting/financial-statements", featureKey: "accounting.financial-statements" },
  { scope: "page", prefix: "/accounting/sales", featureKey: "accounting.ar" },
  { scope: "page", prefix: "/accounting/purchases", featureKey: "accounting.ap" },
  { scope: "page", prefix: "/accounting/banking", featureKey: "accounting.banking" },
  { scope: "page", prefix: "/accounting/assets", featureKey: "accounting.fixed-assets" },
  { scope: "page", prefix: "/accounting/budgets", featureKey: "accounting.budgets" },
  { scope: "page", prefix: "/accounting/cost-centers", featureKey: "accounting.cost-centers" },
  { scope: "page", prefix: "/accounting/currency", featureKey: "accounting.multi-currency" },
  { scope: "page", prefix: "/accounting/tax", featureKey: "accounting.tax" },
  { scope: "page", prefix: "/accounting/fiscalisation", featureKey: "accounting.zimra.fiscalisation" },
  { scope: "page", prefix: "/accounting", featureKey: "accounting.core" },

  { scope: "page", prefix: "/schools/documents", featureKey: "schools.core" },
  { scope: "page", prefix: "/schools/academics", featureKey: "schools.core" },
  { scope: "page", prefix: "/schools/timetable", featureKey: "schools.core" },
  { scope: "page", prefix: "/schools/assessments", featureKey: "schools.results" },
  { scope: "page", prefix: "/schools/finance", featureKey: "schools.fees" },
  { scope: "page", prefix: "/schools/notices", featureKey: "schools.core" },
  { scope: "page", prefix: "/schools/reports", featureKey: "schools.core" },
  { scope: "page", prefix: "/schools/admissions", featureKey: "schools.admissions" },
  { scope: "page", prefix: "/schools/students", featureKey: "schools.students" },
  { scope: "page", prefix: "/schools/classes", featureKey: "schools.core" },
  { scope: "page", prefix: "/schools/subjects", featureKey: "schools.core" },
  { scope: "page", prefix: "/schools/attendance", featureKey: "schools.attendance" },
  { scope: "page", prefix: "/schools/fees", featureKey: "schools.fees" },
  { scope: "page", prefix: "/schools/boarding", featureKey: "schools.boarding" },
  { scope: "page", prefix: "/schools/teachers", featureKey: "schools.teachers" },
  { scope: "page", prefix: "/schools/results/moderation", featureKey: "schools.results" },
  { scope: "page", prefix: "/schools/results/publish", featureKey: "schools.results" },
  { scope: "page", prefix: "/schools/results", featureKey: "schools.results" },
  { scope: "page", prefix: "/schools/portal/parent", featureKey: "schools.portal.parent" },
  { scope: "page", prefix: "/schools/portal/student", featureKey: "schools.portal.student" },
  { scope: "page", prefix: "/schools/portal/teacher", featureKey: "schools.portal.teacher" },
  { scope: "page", prefix: "/schools", featureKey: "schools.core" },

  { scope: "page", prefix: "/autos/inventory", featureKey: "autos.inventory" },
  { scope: "page", prefix: "/autos/leads", featureKey: "autos.leads" },
  { scope: "page", prefix: "/autos/deals", featureKey: "autos.deals" },
  { scope: "page", prefix: "/autos/financing", featureKey: "autos.financing" },
  { scope: "page", prefix: "/autos", featureKey: "autos.core" },
  { scope: "page", prefix: "/car-sales/inventory", featureKey: "autos.inventory" },
  { scope: "page", prefix: "/car-sales/leads", featureKey: "autos.leads" },
  { scope: "page", prefix: "/car-sales/deals", featureKey: "autos.deals" },
  { scope: "page", prefix: "/car-sales/financing", featureKey: "autos.financing" },
  { scope: "page", prefix: "/car-sales", featureKey: "autos.core" },

  { scope: "page", prefix: "/thrift/intake", featureKey: "thrift.intake" },
  { scope: "page", prefix: "/thrift/catalog", featureKey: "thrift.catalog" },
  { scope: "page", prefix: "/thrift/checkout", featureKey: "thrift.checkout" },
  { scope: "page", prefix: "/thrift/sales", featureKey: "thrift.checkout" },
  { scope: "page", prefix: "/thrift/pos", featureKey: "thrift.checkout" },
  { scope: "page", prefix: "/thrift", featureKey: "thrift.core" },

  { scope: "page", prefix: "/portal/pos", featureKey: "thrift.checkout" },
  { scope: "page", prefix: "/portal/parent", featureKey: "schools.portal.parent" },
  { scope: "page", prefix: "/portal/student", featureKey: "schools.portal.student" },
  { scope: "page", prefix: "/portal/teacher", featureKey: "schools.portal.teacher" },
  { scope: "page", prefix: "/portal/schools", featureKey: "portal.schools" },
  { scope: "page", prefix: "/portal/autos", featureKey: "portal.autos" },
  { scope: "page", prefix: "/portal/car-sales", featureKey: "portal.autos" },
  { scope: "page", prefix: "/portal/thrift", featureKey: "portal.thrift" },
  { scope: "page", prefix: "/portal", featureKey: "portal.core" },

  { scope: "page", prefix: "/gold/intake/pours", featureKey: "gold.intake.pours" },
  { scope: "page", prefix: "/gold/intake/purchases", featureKey: "gold.intake.pours" },
  { scope: "page", prefix: "/gold/transit/dispatches", featureKey: "gold.dispatches" },
  { scope: "page", prefix: "/gold/dispatch", featureKey: "gold.dispatches" },
  { scope: "page", prefix: "/gold/settlement/receipts", featureKey: "gold.receipts" },
  { scope: "page", prefix: "/gold/receipt", featureKey: "gold.receipts" },
  { scope: "page", prefix: "/gold/reconciliation", featureKey: "gold.reconciliation" },
  { scope: "page", prefix: "/gold/exceptions", featureKey: "gold.exceptions" },
  { scope: "page", prefix: "/gold/audit", featureKey: "gold.audit-trail" },
  { scope: "page", prefix: "/gold/payouts", featureKey: "gold.payouts" },
  { scope: "page", prefix: "/gold/settlement/payouts", featureKey: "gold.payouts" },
  { scope: "page", prefix: "/gold/prices", featureKey: "gold.home" },
  { scope: "page", prefix: "/gold", featureKey: "gold.home" },

  { scope: "page", prefix: "/scrap-metal/purchases", featureKey: "scrap-metal.purchases" },
  { scope: "page", prefix: "/scrap-metal/batches", featureKey: "scrap-metal.batches" },
  { scope: "page", prefix: "/scrap-metal/sales", featureKey: "scrap-metal.sales" },
  { scope: "page", prefix: "/scrap-metal/pricing", featureKey: "scrap-metal.pricing" },
  { scope: "page", prefix: "/scrap-metal", featureKey: "scrap-metal.home" },

  { scope: "page", prefix: "/compliance", featureKey: "compliance.overview" },
  { scope: "page", prefix: "/management/master-data/hr/departments", featureKey: "hr.employees" },
  { scope: "page", prefix: "/management/master-data/hr/job-grades", featureKey: "hr.employees" },
  { scope: "page", prefix: "/management/master-data/operations/sites", featureKey: "admin.sites-sections" },
  { scope: "page", prefix: "/management/master-data/operations/sections", featureKey: "admin.sites-sections" },
  { scope: "page", prefix: "/management/master-data/operations/downtime-codes", featureKey: "maintenance.breakdowns" },
  { scope: "page", prefix: "/management/master-data/operations/gold-expense-types", featureKey: "gold.payouts" },
  { scope: "page", prefix: "/management/master-data", featureKey: "admin.sites-sections" },
  { scope: "page", prefix: "/management/users/create", featureKey: "admin.user-management.create" },
  { scope: "page", prefix: "/management/users/status", featureKey: "admin.user-management.status" },
  { scope: "page", prefix: "/management/users/password-reset", featureKey: "admin.user-management.password-reset" },
  { scope: "page", prefix: "/management/users/role-change", featureKey: "admin.user-management.role-change" },
  { scope: "page", prefix: "/management/users", featureKey: "admin.user-management.directory" },
  { scope: "page", prefix: "/user-management/create", featureKey: "admin.user-management.create" },
  { scope: "page", prefix: "/user-management/status", featureKey: "admin.user-management.status" },
  { scope: "page", prefix: "/user-management/password-reset", featureKey: "admin.user-management.password-reset" },
  { scope: "page", prefix: "/user-management/role-change", featureKey: "admin.user-management.role-change" },
  { scope: "page", prefix: "/user-management", featureKey: "admin.user-management.directory" },
  { scope: "page", prefix: "/attendance", featureKey: "ops.attendance.mark" },
  { scope: "page", prefix: "/shift-report", featureKey: "ops.shift-report.submit" },
  { scope: "page", prefix: "/plant-report", featureKey: "ops.plant-report.submit" },

  { scope: "page", prefix: "/reports/cctv-events", featureKey: "reports.cctv-events" },
  { scope: "page", prefix: "/reports/compliance-incidents", featureKey: "reports.compliance-incidents" },
  { scope: "page", prefix: "/reports/downtime", featureKey: "reports.downtime-analytics" },
  { scope: "page", prefix: "/reports/maintenance-work-orders", featureKey: "reports.maintenance-work-orders" },
  { scope: "page", prefix: "/reports/maintenance-equipment", featureKey: "reports.maintenance-equipment" },
  { scope: "page", prefix: "/reports/gold-chain", featureKey: "reports.gold-chain" },
  { scope: "page", prefix: "/reports/gold-receipts", featureKey: "reports.gold-receipts" },
  { scope: "page", prefix: "/reports/audit-trails", featureKey: "reports.audit-trails" },
  { scope: "page", prefix: "/reports/fuel-ledger", featureKey: "reports.fuel-ledger" },
  { scope: "page", prefix: "/reports/stores-movements", featureKey: "reports.stores-movements" },
  { scope: "page", prefix: "/reports/attendance", featureKey: "reports.attendance" },
  { scope: "page", prefix: "/reports/shift", featureKey: "reports.shift" },
  { scope: "page", prefix: "/reports/plant", featureKey: "reports.plant" },
  { scope: "page", prefix: "/reports", featureKey: "reports.dashboard" },
];

export const API_FEATURE_ROUTES: FeatureRouteEntry[] = [
  { scope: "api", prefix: "/api/notifications/push-subscriptions", featureKey: "core.notifications.push" },
  { scope: "api", prefix: "/api/notifications", featureKey: "core.notifications.center" },
  { scope: "api", prefix: "/api/settings/branding/domain/verify", featureKey: "core.branding.custom-domain" },
  { scope: "api", prefix: "/api/settings/branding/domain", featureKey: "core.branding.custom-domain" },
  { scope: "api", prefix: "/api/settings/branding", featureKey: "core.branding.manage" },
  { scope: "api", prefix: "/api/document-templates", featureKey: "core.branding.manage" },

  { scope: "api", prefix: "/api/users/create", featureKey: "admin.user-management.create" },
  { scope: "api", prefix: "/api/users/status", featureKey: "admin.user-management.status" },
  { scope: "api", prefix: "/api/users/password-reset", featureKey: "admin.user-management.password-reset" },
  { scope: "api", prefix: "/api/users/role-change", featureKey: "admin.user-management.role-change" },
  { scope: "api", prefix: "/api/users/access/reset", featureKey: "admin.user-management.feature-access" },
  { scope: "api", prefix: "/api/users/access", featureKey: "admin.user-management.feature-access" },
  { scope: "api", prefix: "/api/users", featureKey: "admin.user-management.directory" },
  { scope: "api", prefix: "/api/sites", featureKey: "admin.sites-sections" },
  { scope: "api", prefix: "/api/sections", featureKey: "admin.sites-sections" },
  { scope: "api", prefix: "/api/payroll/config", featureKey: "admin.payroll-config" },

  { scope: "api", prefix: "/api/cctv/streams", featureKey: "cctv.streaming-control" },
  { scope: "api", prefix: "/api/cctv/stream-token", featureKey: "cctv.streaming-control" },
  { scope: "api", prefix: "/api/cctv/playback", featureKey: "cctv.playback" },
  { scope: "api", prefix: "/api/cctv/access-logs", featureKey: "cctv.access-logs" },
  { scope: "api", prefix: "/api/cctv/events", featureKey: "cctv.events" },
  { scope: "api", prefix: "/api/cctv/cameras", featureKey: "cctv.cameras" },
  { scope: "api", prefix: "/api/cctv/nvrs", featureKey: "cctv.nvrs" },

  { scope: "api", prefix: "/api/shift-reports", featureKey: "ops.shift-report.submit" },
  { scope: "api", prefix: "/api/attendance", featureKey: "ops.attendance.mark" },
  { scope: "api", prefix: "/api/plant-reports", featureKey: "ops.plant-report.submit" },

  { scope: "api", prefix: "/api/payroll", featureKey: "hr.payroll" },
  { scope: "api", prefix: "/api/disbursements", featureKey: "hr.disbursements" },
  { scope: "api", prefix: "/api/compensation", featureKey: "hr.compensation-rules" },
  { scope: "api", prefix: "/api/employee-payments", featureKey: "hr.salaries" },
  { scope: "api", prefix: "/api/approvals/history", featureKey: "hr.approvals-history" },
  { scope: "api", prefix: "/api/hr/incidents", featureKey: "hr.incidents" },
  { scope: "api", prefix: "/api/hr/disciplinary-actions", featureKey: "hr.disciplinary-actions" },
  { scope: "api", prefix: "/api/hr/payout-batches", featureKey: "hr.gold-payouts" },
  { scope: "api", prefix: "/api/hr/shift-group-schedules", featureKey: "hr.employees" },
  { scope: "api", prefix: "/api/hr/shift-groups", featureKey: "hr.employees" },
  { scope: "api", prefix: "/api/departments", featureKey: "hr.employees" },
  { scope: "api", prefix: "/api/job-grades", featureKey: "hr.employees" },
  { scope: "api", prefix: "/api/employees", featureKey: "hr.employees" },

  { scope: "api", prefix: "/api/gold/dispatches", featureKey: "gold.dispatches" },
  { scope: "api", prefix: "/api/gold/receipts", featureKey: "gold.receipts" },
  { scope: "api", prefix: "/api/gold/pours", featureKey: "gold.intake.pours" },
  { scope: "api", prefix: "/api/gold/purchases", featureKey: "gold.intake.pours" },
  { scope: "api", prefix: "/api/gold/corrections", featureKey: "gold.reconciliation" },
  { scope: "api", prefix: "/api/gold/shift-allocations", featureKey: "gold.payouts" },
  { scope: "api", prefix: "/api/gold/expense-types", featureKey: "gold.payouts" },
  { scope: "api", prefix: "/api/gold/prices", featureKey: "gold.home" },

  { scope: "api", prefix: "/api/scrap-metal/purchases", featureKey: "scrap-metal.purchases" },
  { scope: "api", prefix: "/api/scrap-metal/batches", featureKey: "scrap-metal.batches" },
  { scope: "api", prefix: "/api/scrap-metal/sales", featureKey: "scrap-metal.sales" },
  { scope: "api", prefix: "/api/scrap-metal/employee-balances", featureKey: "scrap-metal.purchases" },
  { scope: "api", prefix: "/api/scrap-metal/pricing", featureKey: "scrap-metal.pricing" },

  { scope: "api", prefix: "/api/inventory/items", featureKey: "stores.inventory" },
  { scope: "api", prefix: "/api/inventory/movements", featureKey: "stores.movements" },
  { scope: "api", prefix: "/api/stock-locations", featureKey: "stores.inventory" },

  { scope: "api", prefix: "/api/accounting/coa", featureKey: "accounting.chart-of-accounts" },
  { scope: "api", prefix: "/api/accounting/journals", featureKey: "accounting.journals" },
  { scope: "api", prefix: "/api/accounting/periods", featureKey: "accounting.periods" },
  { scope: "api", prefix: "/api/accounting/posting-rules", featureKey: "accounting.posting-rules" },
  { scope: "api", prefix: "/api/accounting/reports/general-ledger", featureKey: "accounting.financial-statements" },
  { scope: "api", prefix: "/api/accounting/reports/trial-balance", featureKey: "accounting.trial-balance" },
  { scope: "api", prefix: "/api/accounting/reports/financials", featureKey: "accounting.financial-statements" },
  { scope: "api", prefix: "/api/accounting/reports/cash-flow", featureKey: "accounting.financial-statements" },
  { scope: "api", prefix: "/api/accounting/hubs/receivables-summary", featureKey: "accounting.ar" },
  { scope: "api", prefix: "/api/accounting/hubs/payables-summary", featureKey: "accounting.ap" },
  {
    scope: "api",
    prefix: "/api/accounting/hubs/financial-reports-summary",
    featureKey: "accounting.financial-statements",
  },
  { scope: "api", prefix: "/api/accounting/reports/ar-aging", featureKey: "accounting.ar" },
  { scope: "api", prefix: "/api/accounting/reports/customer-statement", featureKey: "accounting.ar" },
  { scope: "api", prefix: "/api/accounting/reports/ap-aging", featureKey: "accounting.ap" },
  { scope: "api", prefix: "/api/accounting/reports/vendor-statement", featureKey: "accounting.ap" },
  { scope: "api", prefix: "/api/accounting/reports/vat-summary", featureKey: "accounting.tax" },
  { scope: "api", prefix: "/api/accounting/vat-returns", featureKey: "accounting.tax" },
  { scope: "api", prefix: "/api/accounting/closing", featureKey: "accounting.periods" },
  { scope: "api", prefix: "/api/accounting/payment-ledger", featureKey: "accounting.core" },
  { scope: "api", prefix: "/api/accounting/sales", featureKey: "accounting.ar" },
  { scope: "api", prefix: "/api/accounting/sales/quotations", featureKey: "accounting.ar" },
  { scope: "api", prefix: "/api/accounting/purchases", featureKey: "accounting.ap" },
  { scope: "api", prefix: "/api/accounting/banking", featureKey: "accounting.banking" },
  { scope: "api", prefix: "/api/accounting/assets", featureKey: "accounting.fixed-assets" },
  { scope: "api", prefix: "/api/accounting/budgets", featureKey: "accounting.budgets" },
  { scope: "api", prefix: "/api/accounting/cost-centers", featureKey: "accounting.cost-centers" },
  { scope: "api", prefix: "/api/accounting/currency", featureKey: "accounting.multi-currency" },
  { scope: "api", prefix: "/api/accounting/tax", featureKey: "accounting.tax" },
  { scope: "api", prefix: "/api/accounting/fiscalisation", featureKey: "accounting.zimra.fiscalisation" },
  { scope: "api", prefix: "/api/accounting", featureKey: "accounting.core" },

  { scope: "api", prefix: "/api/schools/admissions", featureKey: "schools.admissions" },
  { scope: "api", prefix: "/api/schools/students", featureKey: "schools.students" },
  { scope: "api", prefix: "/api/schools/guardians", featureKey: "schools.students" },
  { scope: "api", prefix: "/api/schools/enrollments", featureKey: "schools.admissions" },
  { scope: "api", prefix: "/api/schools/attendance", featureKey: "schools.attendance" },
  { scope: "api", prefix: "/api/schools/fees", featureKey: "schools.fees" },
  { scope: "api", prefix: "/api/schools/boarding", featureKey: "schools.boarding" },
  { scope: "api", prefix: "/api/schools/teachers", featureKey: "schools.teachers" },
  { scope: "api", prefix: "/api/schools/results", featureKey: "schools.results" },
  { scope: "api", prefix: "/api/schools/portal/parent", featureKey: "schools.portal.parent" },
  { scope: "api", prefix: "/api/schools/portal/student", featureKey: "schools.portal.student" },
  { scope: "api", prefix: "/api/schools/portal/teacher", featureKey: "schools.portal.teacher" },
  { scope: "api", prefix: "/api/schools", featureKey: "schools.core" },
  { scope: "api", prefix: "/api/v2/schools/admissions", featureKey: "schools.admissions" },
  { scope: "api", prefix: "/api/v2/schools/students", featureKey: "schools.students" },
  { scope: "api", prefix: "/api/v2/schools/guardians", featureKey: "schools.students" },
  { scope: "api", prefix: "/api/v2/schools/enrollments", featureKey: "schools.admissions" },
  { scope: "api", prefix: "/api/v2/schools/attendance/sessions", featureKey: "schools.attendance" },
  { scope: "api", prefix: "/api/v2/schools/attendance", featureKey: "schools.attendance" },
  { scope: "api", prefix: "/api/v2/schools/fees", featureKey: "schools.fees" },
  { scope: "api", prefix: "/api/v2/schools/finance", featureKey: "schools.fees" },
  { scope: "api", prefix: "/api/v2/schools/notices", featureKey: "schools.core" },
  { scope: "api", prefix: "/api/v2/schools/boarding", featureKey: "schools.boarding" },
  { scope: "api", prefix: "/api/v2/schools/teachers", featureKey: "schools.teachers" },
  { scope: "api", prefix: "/api/v2/schools/results", featureKey: "schools.results" },
  { scope: "api", prefix: "/api/v2/schools/portal/parent/children", featureKey: "schools.portal.parent" },
  { scope: "api", prefix: "/api/v2/schools/portal/student/me", featureKey: "schools.portal.student" },
  { scope: "api", prefix: "/api/v2/schools/portal/teacher/me", featureKey: "schools.portal.teacher" },
  { scope: "api", prefix: "/api/v2/schools/portal/parent", featureKey: "schools.portal.parent" },
  { scope: "api", prefix: "/api/v2/schools/portal/student", featureKey: "schools.portal.student" },
  { scope: "api", prefix: "/api/v2/schools/portal/teacher", featureKey: "schools.portal.teacher" },
  { scope: "api", prefix: "/api/v2/schools", featureKey: "schools.core" },

  { scope: "api", prefix: "/api/autos/inventory", featureKey: "autos.inventory" },
  { scope: "api", prefix: "/api/autos/leads", featureKey: "autos.leads" },
  { scope: "api", prefix: "/api/autos/deals", featureKey: "autos.deals" },
  { scope: "api", prefix: "/api/autos/financing", featureKey: "autos.financing" },
  { scope: "api", prefix: "/api/autos", featureKey: "autos.core" },
  { scope: "api", prefix: "/api/car-sales/inventory", featureKey: "autos.inventory" },
  { scope: "api", prefix: "/api/car-sales/leads", featureKey: "autos.leads" },
  { scope: "api", prefix: "/api/car-sales/deals", featureKey: "autos.deals" },
  { scope: "api", prefix: "/api/car-sales/financing", featureKey: "autos.financing" },
  { scope: "api", prefix: "/api/car-sales", featureKey: "autos.core" },
  { scope: "api", prefix: "/api/v2/autos/inventory", featureKey: "autos.inventory" },
  { scope: "api", prefix: "/api/v2/autos/leads", featureKey: "autos.leads" },
  { scope: "api", prefix: "/api/v2/autos/deals", featureKey: "autos.deals" },
  { scope: "api", prefix: "/api/v2/autos/financing", featureKey: "autos.financing" },
  { scope: "api", prefix: "/api/v2/autos", featureKey: "autos.core" },
  { scope: "api", prefix: "/api/v2/car-sales/inventory", featureKey: "autos.inventory" },
  { scope: "api", prefix: "/api/v2/car-sales/leads", featureKey: "autos.leads" },
  { scope: "api", prefix: "/api/v2/car-sales/deals", featureKey: "autos.deals" },
  { scope: "api", prefix: "/api/v2/car-sales/financing", featureKey: "autos.financing" },
  { scope: "api", prefix: "/api/v2/car-sales", featureKey: "autos.core" },

  { scope: "api", prefix: "/api/thrift/intake", featureKey: "thrift.intake" },
  { scope: "api", prefix: "/api/thrift/catalog", featureKey: "thrift.catalog" },
  { scope: "api", prefix: "/api/thrift/checkout", featureKey: "thrift.checkout" },
  { scope: "api", prefix: "/api/thrift", featureKey: "thrift.core" },
  { scope: "api", prefix: "/api/v2/thrift/intake", featureKey: "thrift.intake" },
  { scope: "api", prefix: "/api/v2/thrift/catalog", featureKey: "thrift.catalog" },
  { scope: "api", prefix: "/api/v2/thrift/checkout", featureKey: "thrift.checkout" },
  { scope: "api", prefix: "/api/v2/thrift", featureKey: "thrift.core" },

  { scope: "api", prefix: "/api/portal/parent", featureKey: "schools.portal.parent" },
  { scope: "api", prefix: "/api/portal/student", featureKey: "schools.portal.student" },
  { scope: "api", prefix: "/api/portal/teacher", featureKey: "schools.portal.teacher" },
  { scope: "api", prefix: "/api/portal/schools", featureKey: "portal.schools" },
  { scope: "api", prefix: "/api/portal/autos", featureKey: "portal.autos" },
  { scope: "api", prefix: "/api/portal/car-sales", featureKey: "portal.autos" },
  { scope: "api", prefix: "/api/portal/thrift", featureKey: "portal.thrift" },
  { scope: "api", prefix: "/api/portal", featureKey: "portal.core" },
  { scope: "api", prefix: "/api/v2/portal/parent", featureKey: "schools.portal.parent" },
  { scope: "api", prefix: "/api/v2/portal/parent/children", featureKey: "schools.portal.parent" },
  { scope: "api", prefix: "/api/v2/portal/student/me", featureKey: "schools.portal.student" },
  { scope: "api", prefix: "/api/v2/portal/student", featureKey: "schools.portal.student" },
  { scope: "api", prefix: "/api/v2/portal/teacher/me", featureKey: "schools.portal.teacher" },
  { scope: "api", prefix: "/api/v2/portal/teacher", featureKey: "schools.portal.teacher" },
  { scope: "api", prefix: "/api/v2/portal/schools", featureKey: "portal.schools" },
  { scope: "api", prefix: "/api/v2/portal/autos", featureKey: "portal.autos" },
  { scope: "api", prefix: "/api/v2/portal/car-sales", featureKey: "portal.autos" },
  { scope: "api", prefix: "/api/v2/portal/thrift", featureKey: "portal.thrift" },
  { scope: "api", prefix: "/api/v2/portal", featureKey: "portal.core" },

  { scope: "api", prefix: "/api/work-orders", featureKey: "maintenance.work-orders" },
  { scope: "api", prefix: "/api/equipment", featureKey: "maintenance.equipment" },
  { scope: "api", prefix: "/api/analytics/downtime", featureKey: "reports.downtime-analytics" },
  { scope: "api", prefix: "/api/downtime-codes", featureKey: "maintenance.breakdowns" },

  { scope: "api", prefix: "/api/compliance/permits", featureKey: "compliance.permits" },
  { scope: "api", prefix: "/api/compliance/inspections", featureKey: "compliance.inspections" },
  { scope: "api", prefix: "/api/compliance/incidents", featureKey: "compliance.incidents" },
  { scope: "api", prefix: "/api/compliance/training-records", featureKey: "compliance.training-records" },
];

function normalizePath(pathname: string): string {
  const value = pathname.trim();
  if (!value) return "/";
  return value.startsWith("/") ? value : `/${value}`;
}

function sortByPrefixLength<T extends { prefix: string }>(rows: T[]): T[] {
  return [...rows].sort((a, b) => b.prefix.length - a.prefix.length);
}

const PAGE_PREFIX_SORTED = sortByPrefixLength(PAGE_FEATURE_ROUTES);
const API_PREFIX_SORTED = sortByPrefixLength(API_FEATURE_ROUTES);

export function resolveFeatureKeyForPath(pathname: string): string | null {
  const normalizedPath = normalizePath(pathname).toLowerCase();
  const prefixes = normalizedPath.startsWith("/api/") ? API_PREFIX_SORTED : PAGE_PREFIX_SORTED;
  const match = prefixes.find((row) => normalizedPath.startsWith(row.prefix.toLowerCase()));
  return match?.featureKey ?? null;
}

export function getAllRouteFeatureKeys(): string[] {
  return Array.from(new Set([...PAGE_FEATURE_ROUTES, ...API_FEATURE_ROUTES].map((row) => row.featureKey))).sort();
}
